parameters:
  jobName: release
  imageName: windows-2019
  displayName: 'Release Microsoft.PowerShell.ThreadJob to NuGet'

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  displayName: ${{ parameters.displayName }}

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifacts'
    inputs:
      buildType: current
      downloadType: specific
      itemPattern: '**/*.nupkg'
      downloadPath: '$(System.ArtifactsDirectory)'

  - pwsh: |
      Get-ChildItem -Recurse $(System.ArtifactsDirectory)/Microsoft.PowerShell.ThreadJob.*.nupkg
    displayName: 'Capture downloaded artifact'

  -task: 
    displayName: 'Push PSThreadJob artifacts to AzArtifactsFeed'
    inputs:
      command: push
      packagesToPush: '$(System.ArtifactsDirectory)/Microsoft.PowerShell.ThreadJob.*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: AzArtifactsFeed
