parameters:
  jobName: release
  imageName: windows-2019
  displayName: Release Microsoft.PowerShell.ThreadJob to NuGet

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  displayName: ${{ parameters.displayName }}

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifacts'
    inputs:
      buildType: current
      downloadType: specific
      itemPattern: '**/*.nupkg'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'

  - task: NuGetCommand@2
    displayName: 'NuGet push - PSThreadJob release'
    inputs:
      command: push
      packagesToPush: $(System.ArtifactsDirectory)\nupkg\*.nupkg
      nuGetFeedType: external
      publishFeedCredentials:
