name: ThreadJob-ModuleBuild-$(Build.BuildId)
trigger: none
pr: none

schedules:
- cron: '0 3 * * 1'
  displayName: Weekly Build
  branches:
    include:
    - onebranch-pipelines
  always: true

parameters:
  - name: 'publishToPowerShellGallery'
    displayName: 'Publish module to PowerShell gallery'
    type: boolean
    default: false

variables:
  BuildConfiguration: Release
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  WindowsContainerImage: onebranch.azurecr.io/windows/ltsc2022/vse2022:latest

resources:
  repositories:
  - repository: templates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main

extends:
  # https://aka.ms/obpipelines/templates
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    featureFlags:
      WindowsHostVersion:
        Version: 2022
        Network: Netlock
    globalSdl: # https://aka.ms/obpipelines/sdl
      asyncSdl:
        enabled: true
        forStages: [build]
      #credscan:
      #  enabled: true
      #  scanfolder: $(Build.SourcesDirectory)
      #  suppressionsFile: $(Build.SourcesDirectory)\.config\suppress.json
    stages:
    - stage: build
      jobs:
      - job: main
        displayName: Build package
        pool:
          type: windows
        variables:
        - name: ob_outputDirectory
          value: $(Build.SourcesDirectory)/out
        #- name: ob_sdl_credscan_suppressionsFile
        #  value: $(Build.SourcesDirectory)\.config\suppress.json
        steps:
          - pwsh: |
              Write-Verbose -Verbose ((Get-Item $(Build.SourcesDirectory)).FullName)
              Get-ChildItem $(Build.SourcesDirectory) -Recurse -File -Name | Write-Verbose -Verbose
              $manifestData = Import-PowerShellDataFile -Path src/Microsoft.PowerShell.ThreadJob.psd1
              $moduleVersion = $manifestData.ModuleVersion
              Write-Output "##vso[task.setvariable variable=version;isOutput=true]$moduleVersion"
              if ($manifestData.PrivateData.PsData.Prerelease) {
                $prerel = $manifestData.PrivateData.PSData.Prerelease
                $nupkgVersion = "${moduleVersion}-${prerel}"
              } else {
                $nupkgVersion = $moduleVersion
              }
              Write-Output "##vso[task.setvariable variable=nupkgversion;isOutput=true]$nupkgVersion"
            name: package
            displayName: Get version from project properties
          - task: onebranch.pipeline.version@1
            displayName: Set OneBranch version
            inputs:
              system: Custom
              customVersion: $(package.version)
          - task: UseDotNet@2
            displayName: Use .NET SDK
            inputs:
              packageType: sdk
              useGlobalJson: true
          - pwsh: |
              Get-ChildItem | Write-Verbose -Verbose
              .\build.ps1 -clean -Build -BuildConfiguration Release -BuildFramework net8.0
            displayName: Build
          - task: onebranch.pipeline.signing@1
            displayName: Sign 1st-party files
            inputs:
              command: sign
              signing_profile: external_distribution
              search_root: $(Build.SourcesDirectory)/out/Microsoft.PowerShell.ThreadJob
              files_to_sign: |
                **/*.psd1;
                **/*.ps1xml;
                **/Microsoft.PowerShell.*.dll;
          - task: ArchiveFiles@2
            displayName: Zip module
            inputs:
              rootFolderOrFile: $(Build.SourcesDirectory)/out/Microsoft.PowerShell.ThreadJob
              includeRootFolder: false
              archiveType: zip
              archiveFile: out/Microsoft.PowerShell.ThreadJob-v$(package.version).zip
          - pwsh: |
              Install-Module -Name Microsoft.PowerShell.PSResourceGet -Force -Verbose
              .\build.ps1 -Publish
              Write-Verbose -Verbose ((Get-Item .).FullName)
              Write-Verbose -Verbose ((Get-Item $(Build.SourcesDirectory)).FullName)
              Get-ChildItem $(Build.SourcesDirectory) -Recurse -File -Name | Write-Verbose -Verbose
            displayName: Package module
          - task: onebranch.pipeline.signing@1
            displayName: Sign NuGet package
            inputs:
              command: sign
              signing_profile: external_distribution
              search_root: $(Build.SourcesDirectory)
              files_to_sign: "**/*.nupkg"
    - stage: release
      dependsOn: build
      condition: ${{ parameters.publishToPowerShellGallery }}
      variables:
        version: $[ stageDependencies.build.main.outputs['package.version'] ]
        drop: $(Pipeline.Workspace)/drop_build_main
      jobs:
      - job: validation
        displayName: Manual validation
        pool:
          type: agentless
        timeoutInMinutes: 1440
        steps:
        - task: ManualValidation@0
          displayName: Wait 24 hours for validation
          inputs:
            notifyUsers: $(Build.RequestedForEmail)
            instructions: Please validate the release and then publish it!
            timeoutInMinutes: 1440
      - job: publish
        dependsOn: validation
        displayName: Publish to PowerShell Gallery
        pool:
          type: windows
        variables:
          ob_outputDirectory: $(Build.SourcesDirectory)/out/Microsoft.PowerShell.ThreadJob
        steps:
        - download: current
          displayName: Download artifacts
        - task: NuGetCommand@2
          displayName: Publish ConsoleGuiTools to PowerShell Gallery
          inputs:
            command: push
            packagesToPush: $(Build.SourcesDirectory)/out/Microsoft.PowerShell.ThreadJob.$(package.nupkgVersion).nupkg
            nuGetFeedType: external
            publishFeedCredentials: PowerShellGallery-chungjustin