name: ThreadJob-ModuleBuild-$(Build.BuildId)
trigger: none
pr: none

schedules:
- cron: '0 3 * * 1'
  displayName: Weekly Build
  branches:
    include:
    - onebranch-pipelines
  always: true

parameters:
  - name: 'publishOfficialToPowerShellGallery'
    displayName: 'Publish official module to PowerShell gallery'
    type: boolean
    default: false
  - name : 'publishProxyToPowerShellGallery'
    displayName: 'Publish proxy module to PowerShell gallery'
    type: boolean
    default: false
  - name : ReleaseEnvironment
    displayName: 'Release environment'
    type: string
    default: 'Production'

variables:
  BuildConfiguration: Release
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  WindowsContainerImage: onebranch.azurecr.io/windows/ltsc2022/vse2022:latest

resources:
  repositories:
  - repository: templates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main

extends:
  # https://aka.ms/obpipelines/templates
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    release:
      category: NonAzure
    featureFlags:
      WindowsHostVersion:
        Version: 2022
        Network: Netlock
    globalSdl: # https://aka.ms/obpipelines/sdl
      asyncSdl:
        enabled: true
        forStages: [build]
      #credscan:
      #  enabled: true
      #  scanfolder: $(Build.SourcesDirectory)
      #  suppressionsFile: $(Build.SourcesDirectory)\.config\suppress.json
    stages:
    - stage: build
      jobs:
      - job: main
        templateContext:
          sdl:
            codeSignValidation:
              targetPathExclusionPattern: \"^(?!.*\\.nupkg$).*\"
        displayName: Build package
        pool:
          type: windows
        variables:
        - name: ob_outputDirectory
          value: '$(Build.ArtifactStagingDirectory)'
        - name: ob_sdl_sbom_enabled
          value: true
        #- name: ob_sdl_credscan_suppressionsFile
        #  value: $(Build.SourcesDirectory)\.config\suppress.json
        steps:
          - pwsh: |
              Write-Verbose -Verbose $(Build.SourcesDirectory)
              Get-ChildItem $(Build.SourcesDirectory) -Recurse -File -Name | Write-Verbose -Verbose
              $manifestData = Import-PowerShellDataFile -Path src/Microsoft.PowerShell.ThreadJob.psd1
              $moduleVersion = $manifestData.ModuleVersion
              Write-Host "##vso[task.setvariable variable=version;isOutput=true]$moduleVersion"
              $proxyManifestData = Import-PowerShellDataFile -Path src/ThreadJob/ThreadJob.psd1
              $proxyModuleVersion = $proxyManifestData.ModuleVersion
              Write-Host "##vso[task.setvariable variable=proxyVersion;isOutput=true]$proxyModuleVersion"
            name: package
            displayName: Get version from project properties
          - task: onebranch.pipeline.version@1
            displayName: Set OneBranch version
            inputs:
              system: Custom
              customVersion: $(package.version)
          - task: UseDotNet@2
            displayName: Use .NET SDK
            inputs:
              packageType: sdk
              useGlobalJson: true
          - pwsh: |
              Get-ChildItem | Write-Verbose -Verbose
              Register-PSRepository -Name CFS -SourceLocation "https://pkgs.dev.azure.com/powershell/PowerShell/_packaging/powershell/nuget/v2" -InstallationPolicy Trusted
              Install-Module -Repository CFS -Name Microsoft.PowerShell.PSResourceGet -MinimumVersion 1.0.5
              .\build.ps1 -clean -Build -BuildConfiguration Release -BuildFramework netstandard2.0
            displayName: Build
          # Add signing for all files for now.
          - task: onebranch.pipeline.signing@1
            displayName: Sign 1st-party files
            inputs:
              command: sign
              signing_profile: external_distribution
              search_root: $(Build.SourcesDirectory)/out
              files_to_sign: |
                **/*.psd1;
                **/*.ps1xml;
                **/*.psm1;
                **/Microsoft.PowerShell.*.dll;
          - pwsh: |
              Get-ChildItem | Write-Verbose -Verbose
              Write-Verbose -Verbose -Message "Install Microsoft.PowerShell.ThreadJob module"
              Copy-Item -Path $(Build.SourcesDirectory)/out/Microsoft.PowerShell.ThreadJob -Destination ($env:PSModulePath -split ';')[0] -Recurse -Force
              Write-Verbose -Verbose -Message "Test ThreadJob module manifest"
              Test-ModuleManifest -Path $(Build.SourcesDirectory)/out/ThreadJob/ThreadJob.psd1
              .\build.ps1 -Publish
              Write-Verbose -Verbose ((Get-Item .).FullName)
              Write-Verbose -Verbose $(Build.SourcesDirectory)
              Get-ChildItem $(Build.SourcesDirectory) -Recurse -File -Name | Write-Verbose -Verbose
            displayName: Package module
          - task: onebranch.pipeline.signing@1
            displayName: Sign NuGet package
            inputs:
              command: sign
              signing_profile: external_distribution
              search_root: $(Build.SourcesDirectory)
              files_to_sign: "**/*.nupkg"
          - pwsh: |
              Get-ChildItem -Path $(Build.SourcesDirectory)/out -Filter '*.nupkg' -Recurse
                | ForEach-Object {
                  Write-Verbose -Verbose "Copying $($_.FullName) to $(ob_outputDirectory)"
                  Copy-Item -Path $_.FullName -Destination $(ob_outputDirectory) -Force
                }
              Get-ChildItem -Path $(ob_outputDirectory) -Recurse -File -Name | Write-Verbose -Verbose
            displayName: Upload Signed Nupkgs
    - stage: release_official_MicrosoftPowerShellThreadJob_module
      displayName: release official
      variables:
        ob_release_environment: ${{ parameters.ReleaseEnvironment }}
        drop: $(Pipeline.Workspace)/drop_build_main
        version: $[ stageDependencies.build.main.outputs['package.version'] ]
      dependsOn: [build]
      condition: ${{ parameters.publishOfficialToPowerShellGallery }}
      jobs:
      - job: publish
        templateContext:
          inputs:
            - input: pipelineArtifact
              artifactName: drop_build_main
        displayName: Publish to PowerShell Gallery
        pool:
          type: release
          os: windows
        variables:
        - group: ThreadJob_Gallery_API
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              Get-ChildItem "$(Pipeline.Workspace)/" -Recurse | Write-Verbose -Verbose
          displayName: Find Nupkg
        - task: NuGetCommand@2
          displayName: Push Official ThreadJob module to PSGallery
          inputs:
            command: push
            packagesToPush: '$(Pipeline.Workspace)/Microsoft.PowerShell.ThreadJob.$(version).nupkg'
            nuGetFeedType: external
            publishFeedCredentials: 'PSThreadJob-PSGalleryPush'
    - stage: release_proxy_ThreadJob_module
      displayName: release proxy
      variables:
        ob_release_environment: ${{ parameters.ReleaseEnvironment }}
        drop: $(Pipeline.Workspace)/drop_build_main
        version: $[ stageDependencies.build.main.outputs['package.proxyVersion'] ]
      dependsOn: [build]
      condition: ${{ parameters.publishProxyToPowerShellGallery }}
      jobs:
      - job: publish
        templateContext:
          inputs:
            - input: pipelineArtifact
              artifactName: drop_build_main
        displayName: Publish to PowerShell Gallery
        pool:
          type: release
          os: windows
        variables:
        - group: ThreadJob_Gallery_API
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              Get-ChildItem "$(Pipeline.Workspace)/" -Recurse | Write-Verbose -Verbose
          displayName: Find Nupkg
        - task: NuGetCommand@2
          displayName: Push Proxy ThreadJob module to PSGallery
          inputs:
            command: push
            packagesToPush: '$(Pipeline.Workspace)/ThreadJob.$(version).nupkg'
            nuGetFeedType: external
            publishFeedCredentials: 'PSThreadJob-PSGalleryPush'
          